### ISSUE TITLE
Custom sidebar scrollbar

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#441]
My browser started to show up a white scrollbar out of nowhere in the sidebar. It really freaked me out and a bunch of users reported that they always saw the white scrollbar. Therefore I decided to fix it. Here is the CSS code (tested Safari, Chrome and IE, Firefox does not support it):

```css
#full-list {
  scrollbar-face-color: #222a3d;
  scrollbar-track-color: #373f52;
}

#full-list::-webkit-scrollbar {
  width: 1em;
  background-color: #373f52;
}

#full-list::-webkit-scrollbar-thumb {
  background-color: #222a3d;
  border-radius: 16px;
  border: 0.2em solid #373f52;
}
```

The background color is the same as the sidebar color. I am not merging this because I would like @Dignifiedquire to verify and merge it if he agrees. Here is how it looks like:

<img width="331" alt="screen shot 2015-09-28 at 15 14 38" src="https://cloud.githubusercontent.com/assets/9582/10136238/ad8f17ca-65f3-11e5-9c46-c19f65d160be.png">
